---
format: 
  pptx:
    reference-doc: template.pptx
    fig-dpi: 800
editor: visual
params: 
  reporting_quarter: '2024/25 Q3'
  master_files_folder: '1. Master files'
  quarter_string: '24_25_Q3'
  hin_name: 'Yorkshire & Humber'
title: "NatPatSIP - `r params$hin_name` Progression Journeys"
author: "Patient Safety Analysis Team"
---

```{r setup, include=FALSE}
#|echo: false
#|warning: false

# read in required packages
library(here)
library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(readxl)
library(forcats)
library(scales)
library(ggsci)
library(viridis)
library(Microsoft365R)

source('config_sharepoint_location.R')


# params
reporting_quarter <- params$reporting_quarter
master_files_folder <- params$master_files_folder
quarter_string <- params$quarter_string
hin_name <- params$hin_name

# go into share point and download latest data
master_files_dr <- chosenlib$get_item(glue::glue("{base_url}/{master_files_folder}"))

# data upload 
mat_neo_data_file <- master_files_dr$list_files() |> 
  select(name) |> 
  filter(str_detect(name, 
                    # below parameter is generated in read_qart_submissions.R
                    quarter_string)
         ) |>
  as.vector() |>
  unlist() |> 
  unname()

mat_neo_identified_data <- master_files_dr$get_item(str_glue({mat_neo_data_file}))

mat_neo_identified_data$download(dest = here("data", str_glue({mat_neo_data_file})), 
                       overwrite = T)

mat_neo_data <- read.csv(here(str_glue('data/{mat_neo_data_file}'))) |>
  mutate(updated_psc_name = str_remove_all(updated_psc_name, ' HIN'))
```

```{r, include = F}
# attempt 1 - faceted time series showing stage per quarter by trust
# (having all trusts in one plot doesn't work as some follow identical progress journeys)

# NOTE:  commenting out as it has not been decided whether this chart will be used


# data wrangling - potential looped function process
# df=mat_neo_data
# hins=unique(df$updated_psc_name)
# 
# hin_name = "Imperial College Health Partners"
# 
# hin_df <- df |>
#   filter(updated_psc_name == hin_name) |>
#   pivot_longer(cols = magnesium_sulphate:mews,
#                names_to = "intervention_name",
#                values_to = "reported_stage"
#                )
# 
# interventions = unique(hin_df$intervention_name)
# intervention = "maternal_breast_milk"
# intervention_df <- hin_df |>
#   filter(intervention_name == intervention) |>
#   mutate(stage_numeric = str_extract(reported_stage, '[0-9]'))
# 
# plot <- ggplot(intervention_df |> filter(!is.na(stage_numeric)),
#          aes(x = quarter, y = stage_numeric, group = organisation_name_verified)) +
#   geom_line(colour = '#0e668b', size = 1) +
#   labs(x =NULL, 
#          y =NULL, 
#          title = str_glue('{hin_name} - Progression journey of {intervention}'),
#          subtitle = str_glue('Data from 2021/22 Q1 to {reporting_quarter}')
#            )+
#   #facet_grid(rows = vars(api_org_code)) +
#   facet_wrap(~ organisation_name_verified ,
#              ncol = 3,
#              labeller = labeller(organisation_name_verified = label_wrap_gen(width = 25))
#                )+ 
#   theme_minimal() +
#   theme(panel.grid.major.y = element_blank(),
#           axis.text.x = element_text(angle = 90,
#                                      # centre text under tick
#                                      vjust = 0.30),
#           legend.position = 'none',
#           legend.title = element_blank()
#           )
#   
# print(plot)
```

```{r, fig.height=9, fig.width=14, include = F}
# for(hin in hins) {
#   hin_name = hin
#   
#   hin_df <- df |>
#   filter(updated_psc_name == hin_name) |>
#   pivot_longer(cols = magnesium_sulphate:mews,
#                names_to = "intervention_name",
#                values_to = "reported_stage"
#                )
#   
#   interventions = unique(hin_df$intervention_name)
#   intervention = "maternal_breast_milk"
#   
#   intervention_df <- hin_df |>
#     filter(intervention_name == intervention) |>
#     mutate(stage_numeric = str_extract(reported_stage, '[0-9]'))
#   
#   plot <- ggplot(intervention_df |> filter(!is.na(stage_numeric)),
#          aes(x = quarter, y = stage_numeric, group = organisation_name_verified)) +
#   geom_line(colour = '#0e668b', size = 1) +
#   labs(x =NULL, 
#          y =NULL, 
#          title = str_glue('{hin_name} - Progression journey of {intervention}'),
#          subtitle = str_glue('Data from 2021/22 Q1 to {reporting_quarter}')
#            )+
#   #facet_grid(rows = vars(api_org_code)) +
#   facet_wrap(~ organisation_name_verified ,
#              ncol = 3,
#              labeller = labeller(organisation_name_verified = label_wrap_gen(width = 30))
#                )+ 
#   theme_minimal() +
#   theme(panel.grid.major.y = element_blank(),
#           axis.text.x = element_text(angle = 90,
#                                      # centre text under tick
#                                      vjust = 0.30),
#           legend.position = 'none',
#           legend.title = element_blank()
#           )
#   
#   print(plot)
#   }
```

```{r}
# plotting function
progression_plot <- function(df, hin_name, intervention) {
  # filter data to one psc and make long
  hin_df <- df |>
    filter(updated_psc_name == hin_name) |>
    pivot_longer(
      cols = magnesium_sulphate:mews,
      names_to = "intervention_name",
      values_to = "reported_stage"
    )

  # then filter down to one intervention only
  intervention_df <- hin_df |>
    filter(intervention_name == intervention) |>
    mutate(stage_numeric = str_extract(reported_stage, "[0-9]"))

  # handle special PSC cases
  # remove site data fro Kent
  if (hin_name == "Kent Surrey Sussex") {
    intervention_df <- intervention_df |>
      filter(!is.na(api_org_code))
  }

  # re order trusts to show succession history in graph in NWC and SW
  if (hin_name == "North West Coast") {
    all_orgs <- unique(intervention_df$organisation_name_verified)
    orgs_mergers <- c(
      "SOUTHPORT AND ORMSKIRK HOSPITAL NHS TRUST",
      "ST HELENS AND KNOWSLEY TEACHING HOSPITALS NHS TRUST",
      "MERSEY AND WEST LANCASHIRE TEACHING HOSPITALS NHS TRUST"
    )
    orgs_no_mergers <- all_orgs[!all_orgs %in% orgs_mergers]

    intervention_df <- intervention_df |>
      mutate(organisation_name_verified = factor(organisation_name_verified,
        levels = c(orgs_mergers, orgs_no_mergers)
      ))
  }


  if (hin_name == "South West") {
    all_orgs <- unique(intervention_df$organisation_name_verified)
    orgs_mergers <- c(
      "YEOVIL DISTRICT HOSPITAL NHS FOUNDATION TRUST",
      "SOMERSET NHS FOUNDATION TRUST",
      "NORTHERN DEVON HEALTHCARE NHS TRUST",
      "ROYAL DEVON AND EXETER NHS FOUNDATION TRUST",
      "ROYAL DEVON UNIVERSITY HEALTHCARE NHS FOUNDATION TRUST"
    )
    orgs_no_mergers <- all_orgs[!all_orgs %in% orgs_mergers]

    intervention_df <- intervention_df |>
      mutate(organisation_name_verified = factor(organisation_name_verified,
        levels = c(orgs_mergers, orgs_no_mergers)
      ))
  }

  # prepare for graphing 
  
  # clean intervention name string
  intervention_string <- deparse(intervention)

  intervention_title <- intervention_string |>
    str_remove_all('~|"') |> # 1 remove ~ and " added by deparse
    str_replace_all("_", " ") |> # 2 replace _ with blank space
    str_to_title() |> # 3 capitalise clean string into title
    str_replace('Of', 'of') |>
    str_replace('Newtt2', 'NEWTT2') |>
    str_replace('Mews', 'MEWS')
  # 
  # if (intervention_title ==  |  intervention_title == 'mews'){
  #   intervention_title <- str_to_upper(intervention_title)
  #   print(intervention_title)
  # }
    
  # custom colour palette
  my_colours <- c(
    "Stage 7 - Sustained" = "#440154FF",
    "Stage 6 - Spread" = "#443A83FF",
    "Stage 5 - Adoption" = "#31688EFF",
    "Stage 4 - Testing or Implementation" = "#21908CFF",
    "Stage 3 - Decision" = "#35B779FF",
    "Stage 2 - Interest" = "#8FD744FF",
    "Stage 1 - Knowledge" = "#FDE725FF"
  )

  plot <- ggplot(
    intervention_df,
    aes(x = quarter, y = organisation_name_verified)
  ) +
    geom_line(aes(group = organisation_name_verified, colour = reported_stage),
      linewidth = 2
    ) +
    geom_point(aes(group = organisation_name_verified, fill = reported_stage),
      size = 4.5,
      colour = "white",
      pch = 21
    ) +
    labs(
      x = NULL,
      y = NULL,
      title = str_glue("{hin_name} - Progression of {intervention_title}"),
      subtitle = str_glue("Trust level data reported by the PSC up to {reporting_quarter}")
    ) +
    scale_y_discrete(labels = function(y) str_wrap(y, width = 30)) +
    scale_colour_manual(values = my_colours) +
    scale_fill_manual(values = my_colours) +
    theme_minimal() +
    theme(
      panel.grid.major.y = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.30),
      legend.position = "bottom",
      legend.title = element_blank()
    ) +
    guides(
      size = "none",
      colour = guide_legend(nrow = 2, byrow = T)
    )
  print(plot)
}
```

# MatNeoSIP - Optimisation

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "place_of_birth")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "maternal_breast_milk")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "normothermia")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "optimal_cord_management")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "antibiotics")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "corticosteroids")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "magnesium_sulphate")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "caffeine")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "volume_targeted_ventilation")
```

# MatNeoSIP - Deterioration Tools

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "newtt2")
```

## 

```{r, fig.width=14, fig.height=9}
progression_plot(df = mat_neo_data, 
                 hin_name = hin_name, 
                 intervention = "mews")
```
