---
title: "NatPatSIP - Quarterly presentation"
author: "Patient Safety Analysis Team"
format: 
  pptx:
    reference-doc: template.pptx
editor: visual
---

```{r}
#|echo: false
#|warning: false

#read in required packages
library(here)
library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(readxl)
library(forcats)

mat_neo_data <- read_excel(here('data/MatNeoSIP.xlsx'), sheet = 'Data') |>
  clean_names() |>
  rename('stage_7_all' = 'stage_7',
         'quarter' = 'date') |>
  rename_with(~ str_replace(., 'x', 'stage_'), starts_with('x'))
```

# MatNeoSIP 
## Optimisation

```{r}
mat_neo_data |> 
  filter(quarter == '2024/25 Q1') |>
  group_by(psc, magnesium_sulphate, stage_1) |>
  summarise(n = n())
```


```{r}
x <- mat_neo_data |> 
  filter(quarter == '2024/25 Q1') |>
  group_by(psc, optimal_cord_management) |>
  summarise(n = n()) |>
  ungroup() |>
  group_by(psc) |>
  mutate(total = sum(n),
         percentage = round((n/total)*100, 1)
         ) |>
  ungroup()

head(x)
```


```{r}
blues <- rev(brewer_pal()(7)) #blues in reversed order 
  
x |>
  ggplot(aes(x = forcats::fct_rev(psc), #reverse alphabetical order
             y = percentage,
             fill = forcats::fct_rev(optimal_cord_management) #reverse stage order
             )
         )+
  geom_bar(stat = 'identity',
           position = 'stack',
           size = 11
           ) +
  scale_fill_manual(values = blues) +
  coord_flip() +
  geom_text(aes(label = paste0(round(percentage), #rounding to no decimal places here
                               '%') #so bars stack to 100 or as close as possible
                ),
          colour = 'white',
          position = position_stack(vjust = 0.5)
          ) +
  labs(title = 'title') + 
  theme_classic() + 
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.position = 'bottom'
        )
```

