---
title: "NatPatSIP - PSC Presentation"
author: "Patient Safety Analysis Team"
format: 
  pptx:
    reference-doc: template.pptx
    fig-dpi: 800
editor: visual
params: 
  reporting_quarter: '2024/25 Q3'
  master_files_folder: '1. Master files'
  quarter_string: '24_25_Q3'
---

```{r setup, include=FALSE}
#|echo: false
#|warning: false

# read in required packages
library(here)
library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(readxl)
library(forcats)
library(scales)
library(ggsci)
library(viridis)
library(Microsoft365R)

source('config_sharepoint_location.R')


# already defined in other scripts but placing here for experimental running
reporting_quarter_end_date <- ymd('2024-12-31') 
reporting_quarter_string <- quarter(reporting_quarter_end_date, 
                                    fiscal_start = 4,
                                    type = 'year_start/end')
previous_quarter_end_date <- reporting_quarter_end_date %m-% months(3)
previous_quarter_string <- quarter(previous_quarter_end_date, 
                                   fiscal_start = 4,
                                   type = 'year_start/end')

quarter_string <- reporting_quarter_string |>
  str_replace_all("/| ", "_")

reporting_quarter = reporting_quarter_string
master_files_folder = master_files_folder
quarter_string = quarter_string

master_files_dr <- chosenlib$get_item(glue::glue("{base_url}/{master_files_folder}"))
# date upload 

mat_neo_data_file <- master_files_dr$list_files() |> 
  select(name) |> 
  filter(str_detect(name, 
                    # below parameter is generated in read_qart_submissions.R
                    quarter_string)
         ) |>
  as.vector() |>
  unlist() |> 
  unname()

mat_neo_identified_data <- master_files_dr$get_item(str_glue({mat_neo_data_file}))

mat_neo_identified_data$download(dest = here("data", str_glue({mat_neo_data_file})), 
                       overwrite = T)

mat_neo_data <- read.csv(here(str_glue('data/{mat_neo_data_file}'))) |>
  mutate(updated_psc_name = str_remove_all(updated_psc_name, ' HIN'))
```


```{r, include = F}
# data wrangling - potential looped function process
df=mat_neo_data
hins=unique(df$updated_psc_name)
```


```{r, include = F}
# attempt 1 - faceted time series showing stage per quarter by trust
# (having all trusts in one plot doesn't work as some follow identical progress journeys)

hin_name = "Imperial College Health Partners"

hin_df <- df |>
  filter(updated_psc_name == hin_name) |>
  pivot_longer(cols = magnesium_sulphate:mews,
               names_to = "intervention_name",
               values_to = "reported_stage"
               )

interventions = unique(hin_df$intervention_name)
intervention = "maternal_breast_milk"
intervention_df <- hin_df |>
  filter(intervention_name == intervention) |>
  mutate(stage_numeric = str_extract(reported_stage, '[0-9]'))

plot <- ggplot(intervention_df |> filter(!is.na(stage_numeric)),
         aes(x = quarter, y = stage_numeric, group = organisation_name_verified)) +
  geom_line(colour = '#0e668b', size = 1) +
  labs(x =NULL, 
         y =NULL, 
         title = str_glue('{hin_name} - Progression journey of {intervention}'),
         subtitle = str_glue('Data from 2021/22 Q1 to {reporting_quarter}')
           )+
  #facet_grid(rows = vars(api_org_code)) +
  facet_wrap(~ organisation_name_verified ,
             ncol = 3,
             labeller = labeller(organisation_name_verified = label_wrap_gen(width = 25))
               )+ 
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
          axis.text.x = element_text(angle = 90,
                                     # centre text under tick
                                     vjust = 0.30),
          legend.position = 'none',
          legend.title = element_blank()
          )
  
print(plot)
```


```{r, fig.height=8, fig.width=12, include = F}
for(hin in hins) {
  hin_name = hin
  
  hin_df <- df |>
  filter(updated_psc_name == hin_name) |>
  pivot_longer(cols = magnesium_sulphate:mews,
               names_to = "intervention_name",
               values_to = "reported_stage"
               )
  
  interventions = unique(hin_df$intervention_name)
  intervention = "maternal_breast_milk"
  
  intervention_df <- hin_df |>
    filter(intervention_name == intervention) |>
    mutate(stage_numeric = str_extract(reported_stage, '[0-9]'))
  
  plot <- ggplot(intervention_df |> filter(!is.na(stage_numeric)),
         aes(x = quarter, y = stage_numeric, group = organisation_name_verified)) +
  geom_line(colour = '#0e668b', size = 1) +
  labs(x =NULL, 
         y =NULL, 
         title = str_glue('{hin_name} - Progression journey of {intervention}'),
         subtitle = str_glue('Data from 2021/22 Q1 to {reporting_quarter}')
           )+
  #facet_grid(rows = vars(api_org_code)) +
  facet_wrap(~ organisation_name_verified ,
             ncol = 3,
             labeller = labeller(organisation_name_verified = label_wrap_gen(width = 30))
               )+ 
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
          axis.text.x = element_text(angle = 90,
                                     # centre text under tick
                                     vjust = 0.30),
          legend.position = 'none',
          legend.title = element_blank()
          )
  
  print(plot)
  }
```



progression chart: connected dots
```{r, fig.width=12, fig.length=10}
hin_name = "Kent Surrey Sussex"

hin_df <- df |>
  filter(updated_psc_name == hin_name) |>
  pivot_longer(cols = magnesium_sulphate:mews,
               names_to = "intervention_name",
               values_to = "reported_stage"
               )

interventions = unique(hin_df$intervention_name)
intervention = "maternal_breast_milk"
intervention_df <- hin_df |>
  filter(intervention_name == intervention) |>
  mutate(stage_numeric = str_extract(reported_stage, '[0-9]'))


# remove site data
if (hin_name == "Kent Surrey Sussex"){
  intervention_df <- intervention_df |>
    filter(!is.na(api_org_code))
}

# re order trusts to show succession history in graph 
if (hin_name == "North West Coast"){
  all_orgs <- unique(intervention_df$organisation_name_verified) 
  orgs_mergers <- c('SOUTHPORT AND ORMSKIRK HOSPITAL NHS TRUST',
                    'ST HELENS AND KNOWSLEY TEACHING HOSPITALS NHS TRUST',
                    'MERSEY AND WEST LANCASHIRE TEACHING HOSPITALS NHS TRUST'
                    )
  orgs_no_mergers <- all_orgs[!all_orgs %in% orgs_mergers]
  
  intervention_df <- intervention_df |>
    mutate(organisation_name_verified = factor(organisation_name_verified, 
                                               levels = c(orgs_mergers, orgs_no_mergers))
           )
} 


if (hin_name == "South West"){
  all_orgs <- unique(intervention_df$organisation_name_verified) 
  orgs_mergers <- c('YEOVIL DISTRICT HOSPITAL NHS FOUNDATION TRUST',
                    'SOMERSET NHS FOUNDATION TRUST',
                    'NORTHERN DEVON HEALTHCARE NHS TRUST',
                    'ROYAL DEVON AND EXETER NHS FOUNDATION TRUST',
                    'ROYAL DEVON UNIVERSITY HEALTHCARE NHS FOUNDATION TRUST'
                    )
  orgs_no_mergers <- all_orgs[!all_orgs %in% orgs_mergers]
  
  intervention_df <- intervention_df |>
    mutate(organisation_name_verified = factor(organisation_name_verified, 
                                               levels = c(orgs_mergers, orgs_no_mergers))
           )
}

ggplot(intervention_df, 
       aes(x = quarter, y = organisation_name_verified )
       ) +
  geom_line(aes(group = organisation_name_verified , colour = reported_stage), 
            size = 2 
            ) + #can't specify different linetype
  geom_point(aes(group = organisation_name_verified , fill = reported_stage
                 ),
             size = 4.5,
             colour = 'white',
             pch = 21
             # default shape, circle
             # shape = 23 #diamond - doesn't look good
             #shape = 15 #square
             ) +
  labs(x =NULL, 
       y =NULL, 
       title = str_glue('{hin_name} - Progression chart for {intervention}'),
       subtitle = str_glue('Trust level data reproted by the PSC up to {reporting_quarter}')
         ) +
  scale_y_discrete(labels = function(y) str_wrap(y, width = 30)) +
  scale_colour_manual(values = my_colours) +
  scale_fill_manual(values = my_colours) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.30),
        legend.position = 'bottom',
        legend.title = element_blank()
        ) +
  guides(size = 'none', 
         colour = guide_legend(nrow = 2, byrow = T)
         )
```

```{r, fig.width=12, fig.length=10}
for(hin in hins) {
  hin_name = hin
  
  hin_df <- df |>
    filter(updated_psc_name == hin_name) |>
    pivot_longer(cols = magnesium_sulphate:mews,
                 names_to = "intervention_name",
                 values_to = "reported_stage"
    )

  interventions = unique(hin_df$intervention_name)
  intervention = "maternal_breast_milk"
  intervention_df <- hin_df |>
      filter(intervention_name == intervention) |>
      mutate(stage_numeric = str_extract(reported_stage, '[0-9]'))
  
  
  # remove site data
  if (hin_name == "Kent Surrey Sussex"){
      intervention_df <- intervention_df |>
          filter(!is.na(api_org_code))
  }
  
  # re order trusts to show succession history in graph 
  if (hin_name == "North West Coast"){
      all_orgs <- unique(intervention_df$organisation_name_verified) 
      orgs_mergers <- c('SOUTHPORT AND ORMSKIRK HOSPITAL NHS TRUST',
                        'ST HELENS AND KNOWSLEY TEACHING HOSPITALS NHS TRUST',
                        'MERSEY AND WEST LANCASHIRE TEACHING HOSPITALS NHS TRUST'
      )
      orgs_no_mergers <- all_orgs[!all_orgs %in% orgs_mergers]
      
      intervention_df <- intervention_df |>
          mutate(organisation_name_verified = factor(organisation_name_verified, 
                                                     levels = c(orgs_mergers, orgs_no_mergers))
          )
  } 
  
  
  if (hin_name == "South West"){
      all_orgs <- unique(intervention_df$organisation_name_verified) 
      orgs_mergers <- c('YEOVIL DISTRICT HOSPITAL NHS FOUNDATION TRUST',
                        'SOMERSET NHS FOUNDATION TRUST',
                        'NORTHERN DEVON HEALTHCARE NHS TRUST',
                        'ROYAL DEVON AND EXETER NHS FOUNDATION TRUST',
                        'ROYAL DEVON UNIVERSITY HEALTHCARE NHS FOUNDATION TRUST'
      )
      orgs_no_mergers <- all_orgs[!all_orgs %in% orgs_mergers]
      
      intervention_df <- intervention_df |>
          mutate(organisation_name_verified = factor(organisation_name_verified, 
                                                     levels = c(orgs_mergers, orgs_no_mergers))
          )
  }
  
  plot <- ggplot(intervention_df, 
         aes(x = quarter, y = organisation_name_verified )
  ) +
      geom_line(aes(group = organisation_name_verified , colour = reported_stage), 
                size = 2 
      ) + #can't specify different linetype
      geom_point(aes(group = organisation_name_verified , fill = reported_stage
      ),
      size = 4.5,
      colour = 'white',
      pch = 21
      # default shape, circle
      # shape = 23 #diamond - doesn't look good
      #shape = 15 #square
      ) +
      labs(x =NULL, 
           y =NULL, 
           title = str_glue('{hin_name} - Progression chart for {intervention}'),
           subtitle = str_glue('Trust level data reproted by the PSC up to {reporting_quarter}')
      ) +
      scale_y_discrete(labels = function(y) str_wrap(y, width = 30)) +
      scale_colour_manual(values = my_colours) +
      scale_fill_manual(values = my_colours) +
      theme_minimal() +
      theme(panel.grid.major.y = element_blank(),
            axis.text.x = element_text(angle = 90, vjust = 0.30),
            legend.position = 'bottom',
            legend.title = element_blank()
      ) +
      guides(size = 'none', 
             colour = guide_legend(nrow = 2, byrow = T)
      )
  print(plot)
  }
```






